- name: Créer une zone DNS primaire intégrée à l'Active Directory
  hosts: all
  gather_facts: no
  tasks:
    - name: Créer une zone DNS via PowerShell si elle n'existe pas
      win_shell: |
        $zoneName = "companys.com"
        $zone = Get-DnsServerZone -Name $zoneName -ErrorAction SilentlyContinue
        if (-not $zone) {
          Add-DnsServerPrimaryZone -Name $zoneName -ReplicationScope "Domain" -DynamicUpdate "NonsecureAndSecure"
        } else {
          Write-Output "La zone DNS $zoneName existe déjà."
        }

