- name: Add mailbox user in FortiMail (Server Mode)
  hosts: fortimail2
  gather_facts: no
  vars:
    domain: "site1.com"       # Mail domain (must exist in FortiMail)
    username: "john"
    user_password: "StrongP@ssw0rd!"
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        cookie: "{{ login_response.cookies_string }}"


    - name: List all available domains
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain"
        method: GET
        headers:
          Cookie: "{{ cookie }}"
          Content-Type: application/json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: domain_list
    
    - name: Show available domains
      debug:
        var: domain_list.json.collection  
    - name: List existing mailbox users in FortiMail domain
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/MailUser/*"
        method: GET
        headers:
          Cookie: "{{ cookie }}"
          Content-Type: application/json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: user_list_response
    
    - name: Show list of users
      debug:
        var: user_list_response.json.collection

