- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    new_profile_name: "spf_copyy"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Create a new antispam profile on FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfAntispam/{{ new_profile_name }}"
        method: POST
        headers:
          Content-Type: application/json
          Cookie: "{{ fm_cookie_string }}"
        body:
          name: "{{ new_profile_name }}"           # e.g. spf_custom
          spf_checking: true
          spf_pass_status: true
          action_spf_pass: "accept"                # Or other supported values
          action_spf_soft_fail: "tag"              # Or "reject", "discard", etc.
          bannedword: true
        body_format: json
        validate_certs: no
        status_code: 200
      register: create_profile_response
