
- hosts: fortimail1
  gather_facts: no
  vars:
    new_user: "ghada"
    user_password: "GhadaSecure2025"
    user_domain: "site1.com"
    user_email: "ghada@site1.com"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response
    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"
    - name: Get list of domains
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
        validate_certs: no
      register: domain_list
    
    - name: Show available domains
      debug:
        var: domain_list.json
    - name: List recipient policies with PolicyRcpt
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/site1.com/PolicyRcpt/"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
        validate_certs: no
      register: policy_list
    
    - name: Show recipient policy list
      debug:
        var: policy_list.json

