- hosts: fortimail1
  gather_facts: no
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        fm_cookie: "{{ login_response.set_cookie }}"

    - name: Add a domain to FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/"
        method: POST
        headers:
          Cookie: "{{ fm_cookie }}"
          Content-Type: application/json
        body_format: json
        body:
          domain: "example.com"
        validate_certs: no
        status_code: 201
    - name: Debug SMTP config failure
      debug:
        var: smtp_config_result
