- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    new_profile_name: "spf_copyyy"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Update the antispam profile with custom settings
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfAntispam/spf_copyyy"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body:
          bannedword: false
          spf_checking: true
          spf_pass_status: true
          action_spf_pass: "pass"
          action_spf_soft_fail: "discard"
          # Add more fields as needed
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: update_response

    
    - name: Show raw create_profile_response
      debug:
        var: update_response

