- name: Configure DNS on FortiMail
  hosts: fortimail1
  gather_facts: no
  vars:
    primary_dns: 192.168.111.151
    secondary_dns: 1.1.1.1

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Configure DNS settings on FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/SysDns"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          primary: "{{ primary_dns }}"
          secondary: "{{ secondary_dns }}"
        validate_certs: no
        status_code: 200
      register: dns_config_result

    - name: Show DNS configuration result
      debug:
        var: dns_config_result
