- hosts: fortimail1
  gather_facts: no
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Create Antispam profile for domain2.local
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/site1.com/ProfAntispam/"
        method: POST
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          profile_name: "default_spam_profile"
          spamcheck: true
          spamscore: 5
          spamaction: "tag"   # or reject, discard, quarantine
          tag_subject: "[SPAM]"
        validate_certs: false
        status_code: [200, 201]
      register: antispam_result
