- hosts: fortimail1
  gather_facts: no
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Add domain to FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/Domain/"
        method: POST
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          mkey: "example.com"
          ip: "192.168.111.122"
          port: 25
          is_subdomain: false
          maindomain: "example.com"
          mxflag: 0
          is_association: false
          is_service_domain: false
          recipient_verification: "SMTP"
          ec_status: true
          failed_time: 1
        validate_certs: no
        status_code: [200, 201]
      register: add_domain_response

    - name: Show result
      debug:
        var: add_domain_response


    - name: Get list of domains from FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        validate_certs: no
        status_code: 200
        return_content: yes
      register: domain_list
    
    - name: Afficher la liste des domaines
      debug:
        var: domain_list.json

