- name: Add mailbox user in FortiMail (Server Mode)
  hosts: fortimail
  gather_facts: no
  vars:
    domain: "{{ domain }}"     
    username: "{{ username }}"
    user_password: "StrongP@ssw0rd!"
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        cookie: "{{ login_response.cookies_string }}"

    - name: Add a mailbox user to FortiMail (Server Mode)
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/UserMail/{{ username }}"
        method: POST
        headers:
          Cookie: "{{ cookie }}"
          Content-Type: application/json
        body_format: json
        body:
          mkey: "{{ username }}"
          password: "{{ user_password }}"
          type: 1                  
          displayname: "{{ username }}"
          quota: 1024000        
          status: true
        validate_certs: no
        status_code: 200
      register: add_user_response
    
    - name: Show result of user creation
      debug:
        var: add_user_response.json


