- hosts: fortimail1
  gather_facts: no

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"
    - name: Dump Antispam profile details (get correct field names)
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/site1.com/ProfAntispam/spf_copy"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
        validate_certs: no
        return_content: yes
      register: profile_details

    - name: Show profile fields
      debug:
        var: profile_details.json
    - name: Update Antispam profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/site1.com/ProfAntispam/spf_copy"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: "application/json"
        validate_certs: no
        body_format: json
        body:
          comment: "Modified by Ansible"
          spf_check: true
          spf_check_score: 3
          spam_action: "tag"
          spam_score_threshold: 5
        status_code: [200, 201]
