- hosts: fortimail1
  gather_facts: no

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Create Antispam profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/site1.com/ProfAntispam/spf_copy"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: "application/json"
        validate_certs: no
        body_format: json
        body: >
          {
            "mkey": "spf_copy",
            "comment": "Auto-created via API",
            "mdomain": "site1.com",
            "spf_check": true,
            "spf_check_action": "tag",          # or "reject", "discard", etc.
            "spf_check_score": 3,
            "rbl_check": true,
            "rbl_check_score": 2,
            "spam_tag_action": "tag",           # action if spam is tagged
            "spam_action": "reject",            # action if high spam score
            "spam_score_threshold": 5,
            "header_check": true,
            "header_check_score": 1
          }
        status_code: [200,201]

