- name: Add mailbox user in FortiMail (Server Mode)
  hosts: fortimail2
  gather_facts: no
  vars:
    domain: "site1.com"       # Mail domain (must exist in FortiMail)
    username: "john"
    user_password: "StrongP@ssw0rd!"
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        cookie: "{{ login_response.cookies_string }}"
    - name: List existing mailbox users in FortiMail domain
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/MailUser"
        method: GET
        headers:
          Cookie: "{{ cookie }}"
          Content-Type: application/json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: user_list_response
    
    - name: Show list of users
      debug:
        var: user_list_response.json.collection

    - name: Create mailbox user in FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/MailUser"
        method: POST
        headers:
          Cookie: "{{ cookie }}"
          Content-Type: application/json
        body_format: json
        body:
          mkey: "{{ username }}"
          passwd: "{{ user_password }}"
          type: 0               # 0 = local mailbox user
          status: 1             # 1 = enabled
          profile: "default"    # or specify your custom user profile
          comment: "Created via Ansible"
        validate_certs: no
        return_content: yes
        status_code: 200
      register: user_create_result

    - name: Show result
      debug:
        msg: "Mailbox user created: {{ user_create_result.status }}"
