---
- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    profile_name: "spf_copyyy"
    policy_id: 1     
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"
    - name: Lister les règles d’accès (PolicyRecipient)
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/PolicyRcpt/"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
        validate_certs: no
        return_content: yes
      register: rule_list

    - name: Afficher les règles
      debug:
        var: rule_list.json.collection
        
