---
- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    profile_name: "ghada"
    policy_id: 2     
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

        
    - name: Vérifier que la PolicyRecipient ID {{ policy_id }} existe
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/PolicyRcpt/{{ policy_id }}"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
        validate_certs: no
        status_code: 200
        return_content: yes
      register: policy_check
    - name: Show policy exist
      debug:
        var: policy_check
    - name: Modify PolicyRcpt to apply antispam profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/PolicyIp/{{ policy_id }}"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body:
          antispam: "{{ profile_name }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: update_response

    - name: Show API response
      debug:
        var: update_response
