---
- name: Create Secure IBE Content Profile with Attachment Scan Rules
  hosts: fortimail1
  gather_facts: no
  vars:
    domain: "System"
    profile_name: "IBE-TESTa"
    comment: "Secure IBE profile created via Ansible"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: false
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Create IBE Content Profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfContent/{{ profile_name }}"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        validate_certs: false
        return_content: yes
        status_code: 200
      register: content_profile_response

    - name: Show creation results
      debug:
        msg:
          - "Content profile response: {{ content_profile_response.json }}"
