- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    profile_name: "spf_copyyy"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"
    - name: delete prfil antispam 
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/site1.com/ProfAntispam/{{ profile_name }}"
        method: DELETE
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        validate_certs: no
        status_code: 200
        return_content: yes
      register: delete_response

    - name: Afficher la réponse
      debug:
        var: delete_response        
