---
- hosts: localhost
  gather_facts: no


  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_user }}"
          password: "{{ fortimail_pass }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        fm_cookie: "{{ login_response.set_cookie }}"

    - name: Add domain to FortiMail
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/Domain/domain"
        method: POST
        headers:
          Content-Type: application/json
          Cookie: "{{ fm_cookie }}"
        body:
          mkey: "domain"
          ip: "192.168.111.122"
          port: 25
          is_subdomain: false
          maindomain: "domain"
          mxflag: 0
          is_association: false
          is_service_domain: false
          recipient_verification: "SMTP"
          ec_status: true
          failed_time: 1
        body_format: json
        validate_certs: no
        status_code: [200, 201]
      register: domain_add_response
