- hosts: fortimail
  gather_facts: no
  vars:
    host: "{{ host }}"
  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        fm_cookie: "{{ login_response.set_cookie }}"
    - name: Get FortiMail hostname
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/SysGlobal/"
        method: GET
        headers:
          Cookie: "{{ fm_cookie }}"
          Content-Type: application/json
        return_content: yes
        validate_certs: no
        status_code: 200
      register: login_response
    - name: get All
      debug: 
        var: login_response.json
        
    - name: Change FortiMail hostname
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/SysGlobal/"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie }}"
          Content-Type: application/json
        body_format: json
        body:
          hostname: "{{ host }}"
          
        validate_certs: no
        status_code: 200
