- name: Manage Content Profile in Recipient Policy
  hosts: fortimail
  gather_facts: no

  vars:
    domain: "{{ domain }}"
    policy_id: "{{ policy_id }}"
    content_profile_name: "{{ content_profile_name }}"
    operation: "{{ operation }}"

  tasks:
    - name: Debug selected operation
      debug:
        var: operation

    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Create content profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfContent/{{ content_profile_name }}"
        method: POST
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          name: "{{ content_profile_name }}"
          comments: "Profil contenu créé automatiquement"
        validate_certs: no
        status_code: 200
      when: "'add' in operation"

    - name: Update content profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfContent/{{ content_profile_name }}"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          archive_password: "UserQuarantine"
          office_macro: "UserQuarantine"
          executable: "UserQuarantine"
          multimedia: "pass"
          script_file: "UserQuarantine"
          encrypted_archive: "UserQuarantine"
          unscannable_file: "UserQuarantine"
          file_filter_status: true
        validate_certs: no
        return_content: yes
        status_code: 200
      when: "'update' in operation"

    - name: Associate content profile to recipient policy
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/PolicyRcpt/{{ policy_id }}"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          content: "{{ content_profile_name }}"
        validate_certs: no
        return_content: yes
        status_code: 200
      when: "'associate' in operation"

    - name: Dissociate content profile from recipient policy
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/PolicyRcpt/{{ policy_id }}"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body_format: json
        body:
          content: ""
        validate_certs: no
        return_content: yes
        status_code: 200
      when: "'dissociate' in operation"

    - name: Delete content profile
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfContent/{{ content_profile_name }}"
        method: DELETE
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        validate_certs: no
        return_content: yes
        status_code: 200
      when: "'delete' in operation"
