- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    new_profile_name: "spf_copyyy"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Update the antispam profile 
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfAntispam/spf_copyyy"
        method: PUT
        headers:
          Cookie: "{{ fm_cookie_string }}"
          Content-Type: application/json
        body:
          bannedword: true
          spf_checking: true
          spf_pass_status: true
          spf_fail_status: true
          spf_neutral_status: true
          spf_none_status: true
          spf_perm_error_status: true
          spf_sender_alignment_status: true
          spf_soft_fail_status: true
          spf_temp_error_status: true
          action_spf_pass: "pass"
          action_spf_soft_fail: "UserQuarantine"
          action_dkim: "pass"
          action_dkim_none: "UserQuarantine"
          action_dkim_pass: "pass"
          action_dkim_temp_error: "UserQuarantine"
          action_dmarc: "pass"
          action_dmarc_none: "UserQuarantine"
          action_dmarc_pass: "pass"
          action_dmarc_temp_error: "UserQuarantine"
          action_spf_fail: "UserQuarantine"
          action_spf_neutral: "UserQuarantine"
          action_spf_none: "UserQuarantine"
          action_spf_perm_error: "UserQuarantine"
          action_spf_sender_alignment: "pass"
          action_spf_temp_error: "UserQuarantine"
          dkim_fail_status: true
          dkim_none_status: true
          dkim_pass_status: true
          dkim_status: true
          dkim_temp_error_status: true
          dmarc_fail_status: true
          dmarc_none_status: true
          dmarc_pass_status: true
          dmarc_status : true
          dmarc_temp_error_status : true
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: update_response

    
    - name: Show raw create_profile_response
      debug:
        var: update_response

