- hosts: fortimail1
  gather_facts: no
  vars:
    domain: "site1.com"
    profile_name: "AntiV"

  tasks:
    - name: Login to FortiMail and get session cookie
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/AdminLogin"
        method: POST
        headers:
          Content-Type: application/json
        body:
          name: "{{ fortimail_username }}"
          password: "{{ fortimail_password }}"
        body_format: json
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract session cookie string
      set_fact:
        fm_cookie_string: "{{ login_response.cookies_string }}"

    - name: Récupérer un profil antispam exemple
      uri:
        url: "https://{{ fortimail_ip }}/api/v1/domain/{{ domain }}/ProfAntivirus/{{ profile_name }}"
        method: GET
        headers:
          Cookie: "{{ fm_cookie_string }}"
        validate_certs: no
        return_content: yes
      register: prof_details
    
    - debug:
        var: prof_details.json
