- name: Manage Windows AD users
  hosts: all
  gather_facts: no
  tasks:
    - name: Create or update user 'user2'
      win_user:
        name: user2
        password: "P@ssw0rd123!"
        user_principal_name: user2@site2.com
        groups:
          - "Domain Users"
        state: present
        description: "Managed by Ansible"
