- name: Configurer les interfaces FortiGate
  hosts: fortigate1
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios
  tasks:
    - name: Configurer interface port4
      fortios_system_interface:
        state: "absent"
        access_token: "{{ fortios_access_token }}" 
        system_interface:
          name: "port4"
          ip: "172.29.3.1 255.255.255.0"
          allowaccess: ["ping","https","ssh","http","fgfm"]
          type: "physical"
          alias: "Site1"
          device_identification: "enable"
          lldp_transmission: "enable"
          role: "lan"
          snmp_index: 1

