---
- name: Create an Active Directory user
  hosts: all
  gather_facts: no
  vars:
    new_username: user3
    new_password: "YourSecurePassword123!"
    upn: "user3@site1.com"
    display_name: "User Two"
    ad_ou: "CN=Users,DC=company,DC=com"   # This points to the default Users containe

  tasks:
    - name: Create AD user
      microsoft.ad.user:
        name: "{{ new_username }}"
        firstname: "{{ new_username }}"
        password: "{{ new_password }}"
        upn: "{{ upn }}"
        display_name: "{{ display_name }}"
        path: "{{ ad_ou }}"
        enabled: yes
        groups: 
          set:
            - Domain Users
        state: present
