---
- name: Create an Active Directory user
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows

  vars:
    new_username: user2
    new_password: "YourSecurePassword123!"
    upn: "user2@site1.com"
    display_name: "User Two"
    ad_ou: "OU=Users,DC=company,DC=com"
    groups:
      - "Domain Users"

  tasks:
    - name: Create AD user "{{ new_username }}"
      win_domain_user:
        name: "{{ new_username }}"
        password: "{{ new_password }}"
        user_principal_name: "{{ upn }}"
        display_name: "{{ display_name }}"
        path: "{{ ad_ou }}"
        enabled: yes
        groups: "{{ groups }}"
        state: present
