- name: Configurer les politiques firewall FortiGate
  hosts: fortigate1
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios
  tasks:
    - name: Politique ALLOW_NET
      fortios_firewall_policy:
        access_token: "{{ fortios_access_token }}" 
        state: "present"
        firewall_policy:
          policyid: 1
          name: "ALLOW_NET"
          srcintf: "port1"
          dstintf: "port2"
          action: "accept"
          srcaddr: ["all"]
          dstaddr: ["all"]
          schedule: "always"
          service: ["ALL"]
          logtraffic: "all"
          nat: "enable"

    - name: Politique VPN1
      fortios_firewall_policy:
        access_token: "{{ fortios_access_token }}" 
        state: "present"
        firewall_policy:
          policyid: 2
          name: "VPN1"
          srcintf: "port1"
          dstintf: "to_FW2"
          action: "accept"
          srcaddr: ["port1 address"]
          dstaddr: ["Site2"]
          schedule: "always"
          service: ["ALL"]
          nat: "disable"

    - name: Politique vpnrev
      fortios_firewall_policy:
        access_token: "{{ fortios_access_token }}" 
        state: "present"
        firewall_policy:
          policyid: 3
          name: "vpnrev"
          srcintf: "to_FW2"
          dstintf: "port1"
          action: "accept"
          srcaddr: ["Site2"]
          dstaddr: ["port1 address"]
          schedule: "always"
          service: ["ALL"]
          nat: "disable"

    - name: Politique dnat
      fortinet.fortios_firewall_policy:
        vdom: "root"
        state: present
        firewall_policy:
          policyid: 4
          name: "dnat"
          srcintf: "port3"
          dstintf: "port1"
          action: "accept"
          srcaddr: ["all"]
          dstaddr: ["mail"]
          schedule: "always"
          service: ["ALL"]
          nat: "disable"
