- name: Configurer VPN IPsec phase1
  hosts: fortigate1
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios
  vars:
    fortios_access_token: "{{ lookup('env','FORTIOS_ACCESS_TOKEN') }}"
    ansible_network_os: fortinet.fortios.fortios
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: false
    
  tasks:
    - name: Phase1 interface to_FW2
      fortios_vpn_ipsec_phase1_interface:
        vdom: "root"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase1_interface:
          name: "to_FW2"
          interface: "port2"
          keylife: 172800
          peertype: "any"
          net_device: "disable"
          proposal: "des-sha256"
          remote_gw: "192.168.111.167"
          psksecret: "chiffre"

