- name: Configurer un VIP FortiGate
  hosts: fortigate
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios

  vars:
    fortios_access_token: "{{ lookup('env', 'FORTIOS_ACCESS_TOKEN') }}"
    ansible_connection: httpapi
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: false

  tasks:
    - name: Ajouter VIP
      fortinet.fortios_firewall_vip:
        vdom: "root"
        state: present
        firewall_vip:
          name: "VIP1"
          extip: "20.20.21.4"
          mappedip: "172.29.1.11"
          extintf: "port3"
