---
- name: Configurer un VIP FortiGate avec plus de détails
  hosts: all
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios

  vars:
    fortios_access_token: "{{ lookup('env','FORTIOS_ACCESS_TOKEN') }}"
    ansible_network_os: fortinet.fortios.fortios
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: false

  tasks:
    - name: Configure virtual IP 
      fortios_firewall_vip:
        vdom: "root"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_vip:
          name: "VIP1"                 
          status: "enable"              
          id: "4" 
          extintf: "port3"   
          extip: "20.20.20.5"           
          mappedip:
            - range: "172.29.1.11-172.29.1.15"
          type: "static-nat"
