---
- name: Test API Token Authentication
  hosts: fortigate1
  gather_facts: false
  tasks:
    - name: Get system status
      fortios_system_global:
        vdom: "{{ vdom }}"
      register: result
    - debug:
        var: result
