---
- name: Configure FortiGate via API
  hosts: all
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios

  tasks:
    - name: Create a basic firewall policy
      fortios_firewall_policy:
        state: "present"
        firewall_policy:
          policyid: 6
          name: "allow_web122"
          srcintf: [{"name": "port1"}]
          dstintf: [{"name": "port2"}]
          srcaddr: [{"name": "all"}]
          dstaddr: [{"name": "all"}]
          action: "accept"
          schedule: "always"
          service: [{"name": "HTTP"}]
          logtraffic: "all"
