---
- name: FortiMail - Check system status
  hosts: localhost
  gather_facts: no

  vars:
    fortimail_host: "https://20.20.20.4"  # replace with your IP
    fortimail_user: "apiadmin"
    fortimail_pass: "admin"

  tasks:
    - name: Check FortiMail system status
      uri:
        url: "{{ fortimail_host }}/api/v1/system/status"
        method: GET
        user: "{{ fortimail_user }}"
        password: "{{ fortimail_pass }}"
        force_basic_auth: yes
        validate_certs: no   # set to yes if using valid cert
        return_content: yes
      register: result

    - name: Show result
      debug:
        var: result.json
