---
- name: FortiMail API - Get system status
  hosts: localhost
  gather_facts: no

  vars:
    fortimail_host: "https://20.20.20.4"       # Replace with your real FortiMail IP
    fortimail_user: "{{ fortimail_user }}"     # Passed from credential or survey
    fortimail_pass: "{{ fortimail_pass }}"     # Passed from credential or survey

  tasks:
    - name: Get FortiMail system status
      uri:
        url: "{{ fortimail_host }}/api/v1/SysInterface/"
        method: GET
        user: "{{ fortimail_user }}"
        password: "{{ fortimail_pass }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: result

    - name: Print system status
      debug:
        var: result.json
