---
- name: Change hostname on FortiMail
  hosts: fortimail1
  gather_facts: no
  tasks:
    - name: Set hostname via CLI commands
      raw: |
        config system global
        set hostname nouveau-nom
        end
