- hosts: fortimail1
  vars:
   host: "20.20.20.4"
   username: "admin"
   password: "admin"
#   vdom: "root"
  tasks:
  - name: Try to pass cli cmd ssh
    fortimail:
     action: "ssh"
     host:  "{{  host }}"  
     username: "{{  username}}"  
     password: "{{ password }}"  
     commands: |
               get system interface
               get system status
               execute update now

