---
- name: FortiMail automation example
  hosts: localhost
  gather_facts: no
  vars:
    fortimail_host: "20.20.20.4"
    fortimail_user: "admin"
    fortimail_pass: "admin"
  tasks:
    - name: Login to FortiMail and get session token
      uri:
        url: "http://20.20.20.4/api/v1/AdminLogin/"
        method: POST
        body_format: json
        body:
          username: "{{ fortimail_user }}"
          password: "{{ fortimail_pass }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Show login response
      debug:
        var: login_response.json
