---
- name: FortiMail automation example
  hosts: fortimail1
  gather_facts: no
  vars:
    fortimail_host: "20.20.20.4"
    fortimail_user: "admin"
    fortimail_pass: "admin"
    base_url: "https://{{ fortimail_host }}/api/v1"
  tasks:

    - name: Login to FortiMail and get session token
      uri:
        url: "{{ base_url }}/logincheck"
        method: POST
        body_format: json
        body:
          username: "{{ fortimail_user }}"
          password: "{{ fortimail_pass }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Show login response
      debug:
        var: login_response.json

    - name: Get FortiMail system status
      uri:
        url: "{{ base_url }}/system/status"
        method: GET
        headers:
          Authorization: "Bearer {{ login_response.json.token }}"
        validate_certs: no
        return_content: yes
      register: status_response

    - name: Show system status
      debug:
        var: status_response.json
