---
- name: FortiMail automation example
  hosts: fortimail1
  gather_facts: no
  vars:
    fortimail_host: "20.20.20.4"
    fortimail_user: "admin"
    fortimail_pass: "admin"
    base_url: "http://{{ fortimail_host }}/api/v1"
  tasks:

    - name: Login to FortiMail and get session token
      uri:
        url: "{{ base_url }}/AdminLogin/"
        method: POST
        body_format: json
        body:
          username: "{{ fortimail_user }}"
          password: "{{ fortimail_pass }}"
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Show login response
      debug:
        var: login_response.json
