- name: Test SSH connectivity to FortiMail (safe)
  hosts: fortimail1
  gather_facts: no

  tasks:
    - name: Run a simple command using raw (won't fail for no Python)
      raw: hostname
      register: result

    - name: Show hostname output
      debug:
        var: result.stdout
