---
- name: Send login request to FortiMail API
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Login to FortiMail API
      uri:
        url: "https://20.20.20.4/api/login"
        method: POST
        body_format: json
        body:
          username: "admin"
          password: "admin"
        headers:
          Content-Type: "application/json"
        validate_certs: no
        return_content: yes
      register: login_response
