---
- name: Change hostname on FortiMail via SSH
  hosts: fortimail1
  gather_facts: no
  tasks:
    - name: Set hostname
      raw: |
        ssh admin@{{ ansible_host }} << EOF
        config system global
        set hostname nouveau-nom
        end
        exit
        EOF
