---
- name: Login to FortiMail and capture session
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send login request to FortiMail API
      uri:
        url: "https://20.20.20.4/api/v1/AdminLogin/"
        method: POST
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body:
          username: "admin"
          password: "admin"
        body_format: json
        return_content: yes
        validate_certs: no
        status_code: 200
      register: login_result

    - name: Show login result
      debug:
        var: login_result.json
