---
- name: Change hostname on FortiMail
  hosts: fortimail1
  gather_facts: no
  tasks:
    - name: Change hostname interactively using expect
      community.general.expect:
        command: ssh {{ ansible_user }}@{{ ansible_host }}
        responses:
          'Password:': "{{ ansible_password }}"
          'mail #': "config system global\n"
          'mail (global) #': "set hostname nouveau-nom\n"
          'mail (global) #': "end\n"
          'mail #': "exit\n"
