---
- name: Get Existing Policies list
  hosts: fortigate1
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios
  tasks:
    - name: Get existing Policies 
      fortios_configuration_fact:
        access_token: "{{ fortios_access_token }}"
        selector: "firewall_policy"
      register: firewall_policy

    - name: Print existing Policies
      debug:
        var: firewall_policy
