---
- name: Configurer des routes statiques FortiGate
  hosts: fortigate1
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios
  vars:
    fortios_access_token: "{{ lookup('env', 'FORTIOS_ACCESS_TOKEN') }}"
    ansible_connection: httpapi
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: false
  tasks:
    - name: Route statique vers 172.29.3.0/24 via to_FW2
      fortios_router_static:
        vdom: "root"
        access_token: "{{ fortios_access_token }}" 
        state: "present"
        router_static:
          seq_num: "5"
          dst: "172.29.3.0 255.255.255.0"
          device: "to_FW2"
