---
- name: Configurer des routes statiques FortiGate
  hosts: fortigate1
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  tasks:
    - name: Route statique
      fortios_router_static:
        access_token: "{{ fortios_access_token }}" 
        state: "present"
        router_static:
          seq_num: "5"
          dst: "172.29.3.0 255.255.255.0"
          device: "to_FW2"
