---
- name: Configurer des VIPs FortiGate
  hosts: fortigate3
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  tasks:
    - name: add vip 
      fortios_firewall_vip:
        access_token: "{{ fortios_access_token }}" 
        state: "present"
        firewall_vip:
          name: "mail"
          extip: "192.168.111.120"
          mappedip:
            - range: "172.29.3.12"
          extintf: "port2"
          type: "static-nat"
