- name: Vérifier que FortiGate répond bien
  hosts: fortigate3
  gather_facts: no
  connection: httpapi

  tasks:
    - name: Obtenir le status du système
      fortinet.fortios.fortios_monitor_system_status:
        vdom: root
        access_token: "{{ fortios_access_token }}"
