---
- name: Configurer des routes statiques FortiGate
  hosts: fortigate1
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  tasks:
    - name: Route statique 1
      fortios_router_static:
        access_token: "{{ fortios_access_token }}" 
        state: "absent"
        router_static:
          seq_num: "1"
          dst: "172.29.2.0 255.255.255.0"
          device: "to_FW2"
    - name: Route statique 2
      fortios_router_static:
        access_token: "{{ fortios_access_token }}" 
        state: "absent"
        router_static:
          seq_num: "2"
          dst: "0.0.0.0 0.0.0.0"
          gateway: "20.20.20.1"
          device: "port3"
