---
- name: Configurer DNS
  hosts: fortigate1
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  tasks:
    - name: config dns 
      fortios_system_dns:
        access_token: "{{ fortios_access_token }}" 
        system_dns:
          primary: "192.168.111.151"
          secondary: "172.29.1.11"
