---
- name: Get Existing VIP list
  hosts: fortigate1
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios
  tasks:
    - name: Get existing VIPs
      fortios_configuration_fact:
        access_token: "{{ fortios_access_token }}"
        selector: "firewall_vip"
      register: vip_list

    - name: Print existing VIPs
      debug:
        var: vip_list
