---
- name: Set FortiGate hostname
  hosts: fortigate2
  connection: httpapi
  gather_facts: no

  collections:
    - fortinet.fortios

  tasks:
    - name: Configure system global settings (hostname)
      fortios_system_global:
        vdom: "root" 
        access_token: "{{ fortios_access_token }}"
        system_global:
          hostname: "SITE2-Firewall"
          gui_theme: "onyx"
