---
- name: Set FortiGate hostname
  hosts: fortigate1
  connection: httpapi
  gather_facts: no

  collections:
    - fortinet.fortios

  tasks:
    - name: Configure system global settings (hostname)
      fortios_system_global:
        vdom: "root" 
        access_token: "{{ fortios_access_token }}"
        system_global:
          hostname: "SITE1-FG"
          gui_theme: "retro"
